#:kivy 2.3.1

<CepilloParty>:
    FloatLayout:
        id: game_layout
        
        Image:
            texture: root.asset_m.get_asset("game_background", "image").texture
            allow_stretch: True
            keep_ratio: False
        
        Label:
            id: time_label
            text: "TIEMPO"
            font_size: '30sp'
            size_hint: (0.3, 0.1)
            pos_hint: {'center_x': 0.5, 'top': 0.95}
            color: (1, 1, 1, 1)
        
        Button:
            id: menu_button
            text: 'MENU'
            size_hint: (None, None)
            size: (100, 50)
            pos_hint: {'x': 0.01, 'top': 0.99}
            background_color: (0.8, 0.2, 0.2, 0.8)
            on_press: root._open_menu(self)