#:kivy 2.3.1

#:kivy 2.3.1

<ScoreLabel@Label>:
    font_name: 'main_font'
    font_size: '28sp'
    halign: 'left'
    valign: 'middle'
    color: (1, 0.922, 0.6, 1)
    size_hint: (0.3, None)
    height: 50
    text_size: self.size

<NameLabel@Label>:
    font_name: 'main_font'
    font_size: '28sp'
    halign: 'right'
    valign: 'middle'
    color: (1, 0.922, 0.6, 1)
    size_hint: (0.3, None)
    height: 50
    text_size: self.size


<Menu>:
    size_hint: (1, 1)
    auto_dismiss: False
    background_color: (0, 0, 0, 0.85)

    FloatLayout:
        canvas.before:
            Rectangle:
               
                texture: app.assets.get_asset("menu_bg", "image").texture if app.assets else None
                size: self.size
                pos: self.pos
        
        Image:
            texture: app.assets.get_asset("logo", "image").texture if app.assets else None
            size_hint: (0.8, 0.5)     
            pos_hint: {'center_x': 0.5, 'top': 0.95}
            allow_stretch: True          
            keep_ratio: True        
        
        Button:
            id: play_button
            size_hint: (0.25, 0.3)     
            pos_hint: {'center_x': 0.5, 'center_y': 0.2}
            background_color: (1, 1, 1, 0)
            canvas:
                Rectangle:
                    texture: app.assets.get_asset("play_button", "image").texture if app.assets else None
                    size: self.size
                    pos: self.pos
            on_press: root.game._start_game()
        
        Button:
            id: ranking_button
            size_hint: (0.18, 0.25)
            pos_hint: {'center_x': 0.9, 'center_y': 0.85}
            background_color: (1, 1, 1, 0)
            canvas:
                Rectangle:
                    texture: app.assets.get_asset("ranking_button", "image").texture if app.assets else None
                    size: self.size
                    pos: self.pos
            on_press: root._show_ranking()

        BoxLayout:
            id: day_ranking_box
            orientation: 'vertical'
            size_hint: (0.2, 0.8)
            pos_hint: {'center_x': 0.18, 'center_y': 0.7}
            spacing: 10
            padding: 10

            Label:
                id: day_ranking_title
                text: 'TOP DEL DIA'
                font_name: 'main_font'
                font_size: '40sp'
                size_hint_y: None
                height: 60
                color: (0.823, 0.9, 0.121, 1)
                bold: True

            GridLayout:
                id: day_ranking_grid
                cols: 1
                spacing: [20, 10]
                size_hint_y: None
                height: 250
                
               
                ScoreLabel:
                    id: score_1
                    text: "1. 0"
                
                ScoreLabel:
                    id: score_2
                    text: "2. 0"
                
                ScoreLabel:
                    id: score_3
                    text: "3. 0"
                
                ScoreLabel:
                    id: score_4
                    text: "4. 0"
                
                ScoreLabel:
                    id: score_5
                    text: "5. 0"


<HighScoreLabel@Label>:
    font_name: 'main_font'
    font_size: '35sp'
    halign: 'left'
    valign: 'middle'
    color: (0, 0.29, 0.6785, 1)
    size_hint: (0.3, None)
    height: 50
    text_size: self.size

<HighNameLabel@Label>:
    font_name: 'main_font'
    font_size: '35sp'
    halign: 'right'
    valign: 'middle'
    color: (0, 0.29, 0.6785, 1)
    size_hint: (0.3, None)
    height: 50
    text_size: self.size
    

<Ranking>:
    size_hint: (0.5, 0.9)
    pos_hint: {"center_x": 0.5, "center_y": 0.5}
    overlay_color: (0, 0, 0, 0.9)

    Image:
        texture: app.assets.get_asset("ranking_bg", "image").texture if app.assets else None
        allow_stretch: True
        keep_ratio: False
        size_hint: (1, 1)
        pos_hint: {'x': 0, 'y': 0}
    
    GridLayout:
        id: highscores_grid
        cols: 2
        spacing: [20, 10]
        size_hint: (0.8, 0.55)
        pos_hint: {'center_x': 0.5, 'center_y': 0.5}
    
